export interface RummyApp {
  id: string;
  name: string;
  bonus: string;
  downloads: string;
  minWithdrawal: string;
  downloadLink: string;
  iconUrl: string;
  category: 'Top' | 'New' | 'High Bonus';
  isTrending?: boolean;
}

export const RUMMY_APPS: RummyApp[] = [
  {
    id: 'jungle-haan',
    name: 'Jungle Haan',
    bonus: 'Rs.51',
    downloads: '150K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/jungle_haan_logo_png_1779114514699.png',
    category: 'Top',
    isTrending: true,
  },
  {
    id: 'rummy-boss',
    name: 'Rummy Boss',
    bonus: 'Rs.100',
    downloads: '380K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/boss_rummy_logo_final_1779114701840.png',
    category: 'Top',
    isTrending: true,
  },
  {
    id: 'rummy-wealth',
    name: 'Rummy Wealth',
    bonus: 'Rs.51',
    downloads: '200K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_wealth_logo_v2_1779115748787.png',
    category: 'Top',
  },
  {
    id: 'rummy-noble',
    name: 'Rummy Noble',
    bonus: 'Rs.41',
    downloads: '350K+',
    minWithdrawal: '₹75',
    downloadLink: '#',
    iconUrl: '/images/rummy_noble_logo_1779114643526.png',
    category: 'High Bonus',
    isTrending: true,
  },
  {
    id: 'rummy-mars',
    name: 'Rummy Mars',
    bonus: 'Rs.41',
    downloads: '170K+',
    minWithdrawal: '₹85',
    downloadLink: '#',
    iconUrl: '/images/rummy_mars_logo_1779115945155.png',
    category: 'Top',
  },
  {
    id: 'rummy-leader',
    name: 'Rummy Leader',
    bonus: 'Rs.51',
    downloads: '250K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_leader.webp',
    category: 'New',
  },
  {
    id: 'game-rummy',
    name: 'Game Rummy',
    bonus: 'Rs.75',
    downloads: '184K+',
    minWithdrawal: 'Rs.80',
    downloadLink: '#',
    iconUrl: '/images/Game_Rummy.webp',
    category: 'New',
  },
  {
    id: 'yono-rummy',
    name: 'Yono Rummy',
    bonus: 'Rs.100',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/yono_rummy.webp',
    category: 'High Bonus',
    isTrending: true,
  },
  {
    id: 'msm-bet',
    name: 'MSM BET',
    bonus: 'Rs.71',
    downloads: '250K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/msm_bet.webp',
    category: 'New',
  },
  {
    id: 'rummy-patola',
    name: 'Rummy Patola',
    bonus: 'Rs.41',
    downloads: '390K+',
    minWithdrawal: '₹85',
    downloadLink: '#',
    iconUrl: '/images/rummy_patola.webp',
    category: 'Top',
  },
  {
    id: 'rummy-blast',
    name: 'Rummy Blast',
    bonus: 'Rs.75',
    downloads: '250K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/Rummy_Blast.webp',
    category: 'New',
  },
  {
    id: 'holy-rummy',
    name: 'Holy Rummy',
    bonus: 'Rs.41',
    downloads: '280K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/Holy_Rummy.webp',
    category: 'High Bonus',
  },
  {
    id: 'rummy-pride',
    name: 'Rummy Pride',
    bonus: 'Rs.75',
    downloads: '450K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/Rummy_Pride.jpg',
    category: 'High Bonus',
  },
  {
    id: 'mqm-bet',
    name: 'MQM BET',
    bonus: 'Rs.20',
    downloads: '255K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/MQM_BET.webp',
    category: 'New',
  },
  {
    id: 'hello-rummy',
    name: 'Hello Rummy',
    bonus: 'Rs.71',
    downloads: '450K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/hello_rummy.webp',
    category: 'High Bonus',
  },
  {
    id: 'love-rummy',
    name: 'Love Rummy',
    bonus: 'Rs.51',
    downloads: '460K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/Love_Rummy.webp',
    category: 'Top',
  },
  {
    id: 'dash-rummy',
    name: 'Dash Rummy',
    bonus: 'Rs.75',
    downloads: '410K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/Dash_Rummy.webp',
    category: 'New',
  },
  {
    id: 'rummy-apna',
    name: 'Rummy Apna',
    bonus: 'Rs.41',
    downloads: '430K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_apna.PNG',
    category: 'Top',
  },
  {
    id: 'rummy-buddy',
    name: 'Rummy Buddy',
    bonus: 'Rs.41',
    downloads: '190K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_buddy.webp',
    category: 'New',
  },
  {
    id: 'roz-rummy',
    name: 'Roz Rummy',
    bonus: 'Rs.51',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/Roz_Rummy.webp',
    category: 'Top',
  },
  {
    id: 'rummy-golds',
    name: 'Rummy Golds',
    bonus: 'Rs.41',
    downloads: '168K+',
    minWithdrawal: '₹75',
    downloadLink: '#',
    iconUrl: '/images/Rummy_Gold.webp',
    category: 'High Bonus',
  },
  {
    id: 'rummy-91',
    name: 'Rummy 91',
    bonus: 'Rs.91',
    downloads: '180K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/rummy_91_logo_1779225292123.png',
    category: 'New',
  },
  {
    id: 'rummy-guru',
    name: 'Rummy Guru',
    bonus: 'Rs.41',
    downloads: '10K',
    minWithdrawal: '₹85',
    downloadLink: '#',
    iconUrl: '/images/Rummy_Guru.webp',
    category: 'Top',
  },
  {
    id: 'rummy-alliance',
    name: 'Rummy Alliance',
    bonus: 'Rs.41',
    downloads: '390K+',
    minWithdrawal: '₹75',
    downloadLink: '#',
    iconUrl: '/images/rummy_alliance.PNG',
    category: 'Top',
  },
  {
    id: 'deccan-rummy',
    name: 'Deccan Rummy',
    bonus: 'Rs.51',
    downloads: '470K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: 'https:/api.dicebear.com/7.x/shapes/svg?seed=deccan',
    category: 'High Bonus',
  },
  {
    id: '666e-rummy',
    name: '666E Rummy',
    bonus: 'Rs.51',
    downloads: '500K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/666e_rummy_logo_v2_1779121399166.png',
    category: 'High Bonus',
  },
  {
    id: 'gogo-rummy',
    name: 'GoGo Rummy',
    bonus: 'Rs.51',
    downloads: '200K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/gogo_rummy_logo_v2_1779121381572.png',
    category: 'New',
  },
  {
    id: '66-rummy',
    name: '66 Rummy',
    bonus: 'Rs.51',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/66_rummy_logo_v2_1779121365053.png',
    category: 'Top',
  },
  {
    id: '9ipl-game',
    name: '9IPL Game',
    bonus: 'Rs.20',
    downloads: '170K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/9ipl_game_logo_v2_1779121347560.png',
    category: 'New',
  },
  {
    id: 'abc-rummy',
    name: 'ABC Rummy',
    bonus: 'Rs.75',
    downloads: '510K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/abc_rummy_logo_v2_1779121330769.png',
    category: 'Top',
  },
  {
    id: 'rummy-glee',
    name: 'Rummy Glee',
    bonus: 'Rs.51',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_glee_logo_1779225260394.png',
    category: 'Top',
  },
  {
    id: 'rummy-prime',
    name: 'Rummy Prime',
    bonus: 'Rs.71',
    downloads: '200K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_prime_logo_v2_1779121314774.png',
    category: 'New',
  },
  {
    id: 'good-slots',
    name: 'Good Slots',
    bonus: 'Rs.41',
    downloads: '200K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/good_slots_logo_v2_1779121298165.png',
    category: 'Top',
  },
  {
    id: 'rummy-league',
    name: 'Rummy League',
    bonus: 'Rs.51',
    downloads: '240K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_league_logo_v2_1779121282114.png',
    category: 'New',
  },
  {
    id: 'rummy-soft',
    name: 'Rummy Soft',
    bonus: 'Rs.51',
    downloads: '440K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_soft_logo_1779225275240.png',
    category: 'Top',
  },
  {
    id: 'yes-rummy',
    name: 'Yes Rummy',
    bonus: 'Rs.75',
    downloads: '480K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/yes_rummy_logo_1779121189385.png',
    category: 'High Bonus',
  },
  {
    id: 'rummy-time',
    name: 'Rummy Time',
    bonus: 'Rs.71',
    downloads: '200K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_time_logo_v2_1779121173100.png',
    category: 'Top',
  },
  {
    id: 'rummy-ola',
    name: 'Rummy Ola',
    bonus: 'Rs.51',
    downloads: '385K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_ola.webp',
    category: 'Top',
  },
  {
    id: 'rummy-deity',
    name: 'Rummy Deity',
    bonus: 'Rs.71',
    downloads: '150K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_deity_logo_1779121147807.png',
    category: 'New',
  },
  {
    id: 'rummy-grand',
    name: 'Rummy Grand',
    bonus: 'Rs.20',
    downloads: '200K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/rummy_grand_logo_1779121130667.png',
    category: 'New',
  },
  {
    id: 'ok-rummy',
    name: 'OK Rummy',
    bonus: 'Rs.51',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/ok_rummy_logo_1779121116767.png',
    category: 'Top',
  },
  {
    id: 'rummy-tour',
    name: 'Rummy Tour',
    bonus: 'Rs.75',
    downloads: '270K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_tour_logo_1779225307392.png',
    category: 'New',
  },
  {
    id: 'rummy-east',
    name: 'Rummy East',
    bonus: 'Rs.51',
    downloads: '360K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_east_logo_1779121095779.png',
    category: 'Top',
  },
  {
    id: 'rummy-best',
    name: 'Rummy Best',
    bonus: 'Rs.71',
    downloads: '360K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_best_logo_1779121077942.png',
    category: 'High Bonus',
  },
  {
    id: 'rummy-master',
    name: 'Rummy Master',
    bonus: 'Rs.51',
    downloads: '110K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_master_logo_1779225326294.png',
    category: 'Top',
  },
  {
    id: 'rummy-zone',
    name: 'Rummy Zone',
    bonus: 'Rs.41',
    downloads: '490K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_zone_logo_1779120854231.png',
    category: 'Top',
  },
  {
    id: 'bappa-rummy',
    name: 'Bappa Rummy',
    bonus: 'Rs.20',
    downloads: '470K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/bappa_rummy_logo_1779120836917.png',
    category: 'New',
  },
  {
    id: 'teen-patti-joy',
    name: 'Teen Patti Joy',
    bonus: 'Rs.75',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: 'https:/api.dicebear.com/7.x/shapes/svg?seed=joy',
    category: 'High Bonus',
  },
  {
    id: 'bingo-101',
    name: 'BINGO 101',
    bonus: 'Rs.51',
    downloads: '362K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/bingo_101_logo_1779120819116.png',
    category: 'New',
  },
  {
    id: 'rummy-loot',
    name: 'Rummy Loot',
    bonus: 'Rs.51',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_loot_logo_1779225341914.png',
    category: 'Top',
  },
  {
    id: 'rummy-paisa',
    name: 'Rummy Paisa',
    bonus: 'Rs.51',
    downloads: '260K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_paisa_logo_1779120804020.png',
    category: 'New',
  },
  {
    id: 'ind-rummy',
    name: 'IND Rummy',
    bonus: 'Rs.75',
    downloads: '430K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/ind_rummy_logo_1779120790697.png',
    category: 'Top',
  },
  {
    id: 'rummy-regal',
    name: 'Rummy Regal',
    bonus: 'Rs.20',
    downloads: '450K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/rummy_regal_logo_1779120774021.png',
    category: 'New',
  },
  {
    id: 'rumble-rummy',
    name: 'Rumble Rummy',
    bonus: 'Rs.71',
    downloads: '460K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rumble_rummy_logo_1779120755739.png',
    category: 'High Bonus',
  },
  {
    id: 'rummy-nabob',
    name: 'Rummy Nabob',
    bonus: 'Rs.20',
    downloads: '330K',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/rummy_nabob_logo_v2_1779120707636.png',
    category: 'Top',
  },
  {
    id: 'lcg-bet',
    name: 'LCG BET',
    bonus: 'Rs.95',
    downloads: '500K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/lcg_bet_logo_1779120692189.png',
    category: 'New',
  },
  {
    id: 'hlowin',
    name: 'HloWin',
    bonus: 'Rs.41',
    downloads: '185K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/hlowin_logo_1779120674750.png',
    category: 'New',
  },
  {
    id: 'rummy-meet',
    name: 'Rummy Meet',
    bonus: 'Rs.71',
    downloads: '110K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_meet_logo_1779225356065.png',
    category: 'Top',
  },
  {
    id: 'rummy-a1',
    name: 'Rummy A1',
    bonus: 'Rs.75',
    downloads: '365K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_a1_logo_1779120658063.png',
    category: 'High Bonus',
  },
  {
    id: 'rummy-bharat',
    name: 'Rummy Bharat',
    bonus: 'Rs.41',
    downloads: '200K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: 'https:/api.dicebear.com/7.x/shapes/svg?seed=bharat',
    category: 'Top',
  },
  {
    id: 'yoyo-slots',
    name: 'YoYo Slots',
    bonus: 'Rs.51',
    downloads: '200K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/yoyo_slots_logo_1779120623218.png',
    category: 'New',
  },
  {
    id: 'ek-rummy',
    name: 'Ek Rummy',
    bonus: 'Rs.20',
    downloads: '200K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/ek_rummy_logo_v2_1779120605524.png',
    category: 'New',
  },
  {
    id: 'rummy-apple',
    name: 'Rummy Apple',
    bonus: 'Rs.20',
    downloads: '200K+',
    minWithdrawal: '₹50',
    downloadLink: '/uttam1',
    iconUrl: 'https:/api.dicebear.com/7.x/shapes/svg?seed=apple',
    category: 'New',
  },
  {
    id: 'jaiho-rummy',
    name: 'Jaiho Rummy',
    bonus: 'Rs.51',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/jaiho_rummy_logo_1779120588855.png',
    category: 'High Bonus',
  },
  {
    id: 'rummy-bloc',
    name: 'Rummy Bloc',
    bonus: 'Rs.51',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_bloc_logo_1779120551091.png',
    category: 'Top',
  },
  {
    id: 'rummy-perfect',
    name: 'Rummy Perfect',
    bonus: 'Rs.20',
    downloads: '230K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/rummy_perfect_logo_1779225371285.png',
    category: 'New',
  },
  {
    id: 'rummy-palace',
    name: 'Rummy Palace',
    bonus: 'Rs.71',
    downloads: '420K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_palace_logo_1779120533653.png',
    category: 'Top',
  },
  {
    id: 'rummy-king',
    name: 'Rummy King',
    bonus: 'Rs.75',
    downloads: '160K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_king_logo_1779120520116.png',
    category: 'High Bonus',
  },
  {
    id: 'yoswin',
    name: 'Yoswin',
    bonus: 'Rs.71',
    downloads: '465K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/main_brand_logo_v2_1779187517106.png', // TODO: replace with actual Yoswin logo when available
    category: 'New',
  },
  {
    id: 'rummy-se',
    name: 'Rummy SE',
    bonus: 'Rs.1500',
    downloads: '120K+',
    minWithdrawal: '₹2000',
    downloadLink: '#',
    iconUrl: '/images/rummy_se_logo_1779120485580.png',
    category: 'High Bonus',
  },
  {
    id: 'rummy-try',
    name: 'Rummy Try',
    bonus: 'Rs.75',
    downloads: '400K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_try_logo_1779120467687.png',
    category: 'High Bonus',
  },
  {
    id: 'rummy-villa',
    name: 'Rummy Villa',
    bonus: 'Rs.71',
    downloads: '250K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: 'https:/api.dicebear.com/7.x/shapes/svg?seed=villa',
    category: 'Top',
  },
  {
    id: 'rummy-modern',
    name: 'Rummy Modern',
    bonus: 'Rs.51',
    downloads: '480K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/rummy_modern_logo_1779120451387.png',
    category: 'Top',
  },
  {
    id: 'rummy-good',
    name: 'Rummy Good',
    bonus: 'Rs.71',
    downloads: '290K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_good_logo_1779120433763.png',
    category: 'New',
  },
  {
    id: 'rummy-ares',
    name: 'Rummy Ares',
    bonus: 'Rs.20',
    downloads: '580K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/rummy_ares_logo_1779120397880.png',
    category: 'Top',
  },
  {
    id: 'rummy-gems',
    name: 'Rummy Gems',
    bonus: 'Rs.71',
    downloads: '185K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_gems_logo_1779120380405.png',
    category: 'New',
  },
  {
    id: 'royally-rummy',
    name: 'Royally Rummy',
    bonus: 'Rs.75',
    downloads: '185K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/royally_rummy_logo_1779120362517.png',
    category: 'High Bonus',
  },
  {
    id: 'rummy-most',
    name: 'Rummy Most',
    bonus: 'Rs.20',
    downloads: '320K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/rummy_most_logo_1779120641223.png',
    category: 'Top',
  },
  {
    id: 'mpl-rummy',
    name: 'MPL Rummy',
    bonus: 'Rs.20',
    downloads: '180K+',
    minWithdrawal: '₹50',
    downloadLink: '#',
    iconUrl: '/images/mpl_rummy_logo_1779120345561.png',
    category: 'Top',
  },
  {
    id: 'rummy-adda',
    name: 'Rummy Adda',
    bonus: 'Rs.75',
    downloads: '210K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_adda_logo_1779120329702.png',
    category: 'New',
  },
  {
    id: 'rummy-mate',
    name: 'Rummy Mate',
    bonus: 'Rs.41',
    downloads: '290K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/rummy_mate_logo_1779120312999.png',
    category: 'Top',
  },
  {
    id: 'kash-rummy',
    name: 'Kash Rummy',
    bonus: 'Rs.51',
    downloads: '450K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/kash_rummy_logo_1779120295938.png',
    category: 'Top',
  },
  {
    id: '334-rummy',
    name: '334 Rummy',
    bonus: 'Rs.75',
    downloads: '110K+',
    minWithdrawal: '₹100',
    downloadLink: '#',
    iconUrl: '/images/334_rummy_logo_1779120279038.png',
    category: 'New',
  },
];
